config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  
  resources :products
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  post 'add_to_cart', to: 'products#add_to_cart'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :order, dependent: :destroy
  belongs_to :product, dependent: destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_products
  
  accepts_nested_attributes_for :order_products
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders, dependent: :destroy
  validates :name, presence: true, length: {minimum: 3, maximum: 20}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "Musisz być zalogowany, by wykonać tę operację"
      redirect_to root_path
    end
  end
  
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    @order = Order.new
  end
  
  def create

  end
  
  def show
    @order = Order.find(params[:id])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
def index
        
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    
    def index
       @products = Product.all 
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(product_params)
        @product.save
        redirect_to products_path
    end
    
    def show
      @product = Product.find(params[:id])
    end
    
    def add_to_cart
      @order_product = OrderProduct.new(params)
      @order_product.save
      render 'index'
    end
    
    private
    
    def product_params
      params.require(:product).permit(:name, :price, :volume, :availability, order_products_attributes: [:id, :quantity])
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Pomyślnie zalogowano jako #{user.name}"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Logowanie nie powiodło się. Sprawdź, czy wprowadzone dane są prawidłowe."
      render 'new'
    end
      
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "Pomyślnie wylogowano z aplikacji"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Pomyślnie utworzono nowe konto"
      Order.create(user: @user, status: "cart") #creates a shopping cart for a new user
      redirect_to products_path
    else
      flash.now[:danger] = "Nie udało się pomyślnie utworzyć konta. Sprawdź czy wprowadzone dane są poprawne."
      render 'new'
    end
  end
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mioder", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Produkty", products_path %></li>
        <li><%= link_to "Użytkownicy", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Akcje <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Dodaj nowy produkt", new_product_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !logged_in? %>
          <li><%= link_to "Załóż konto", signup_path %></li>
          <li><%= link_to "Zaloguj się", login_path %></li>
        <%else%>
          <li><%= link_to order_path(current_user.orders.find_by(status: "cart")) do %>
            Koszyk <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <% end %></li>
          <li><%= link_to "Wyloguj", logout_path, method: :delete %></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/orders/show.html.erb
<h1 class="center">Twój koszyk</h1>
<h3 class="center"><%= @order.user.name %>, to są Twoje zakupy</h3>

app/views/pages/index.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>Mioder</title>
</head>
<body>
  <div class="center jumbotron">
    <h1>Mioder</h1>
    <h3>Zamów miodek do Warszawy :)</h3>
    <p><%=link_to "Załóż konto", signup_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</body>
</html> 

app/views/products/_form.html.erb
<div class='row'>
  <div class="col-sm-12">
    <%= form_for(@product, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label">Nazwa</p>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nazwa produktu", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label">Cena</p>
        </div>
        <div class="col-sm-8">
          <%= f.number_field :price, class: "form-control", placeholder: 0.00, min: 0, step: 0.25, autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label">Wielkość opakowania</p>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :volume, class: "form-control", placeholder: "Wielkość opakowania", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label">Dostępność</p>
        </div>
        <div class="col-sm-8">
          <%= f.select :availability, ["Dostępny", "Niedostępny", "Wymaga sprawdzenia"]%>
        </div>
      </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: 'btn btn-primary btn-lg' %>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/products/_product_list.html.erb
<% products.each do |product| %>
    <div class ="row">
        <div class="col-md-8 col-md-offset-2">
            <div class = "well">
                <h4><%= link_to product.name, product_path(product) %></h4>
                Cena: <%= product.price %> zł | Wielkość Opakowania: <%= product.volume %> | Dostępność: <%= product.availability %>
                
                <%= link_to add_to_cart_path(product: product, order: current_user.orders.find_by(status: 'cart'), quantity: 1), method: :post do %>
                  <div class="btn btn-warning"><i class="fa fa-shopping-cart" aria-hidden="true"></i></div>
                <% end %>
            </div>
        </div>
    </div>
<%end%>

app/views/products/index.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>Mioder</title>
</head>
<body>
<h1 align="center">Dostępne produkty</h1>
<%= render "product_list", products: @products%>
</body>
</html> 

app/views/products/new.html.erb
<h1 class="center">Dodaj produkt</h1>

<%= render 'form' %>

app/views/products/show.html.erb
 <!DOCTYPE html>
<html>
<head>
<title>Mioder</title>
</head>
<body>
<h1 align="center"><%= @product.name %></h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="well">
      <ul>
        <li>Cena: <%=@product.price%></li>
        <li>Wielkość opakowania: <%=@product.volume%></li>
        <li>Dostępność: <%=@product.availability%></li>
      </ul>
    </div>    
  </div>
</div>

</body>
</html> 

app/views/users/_form.html.erb
<div class='row'>
  <div class="col-sm-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f|  %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label"><% f.label :name %> Imię i nazwisko</p>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter user name", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label"><% f.label :email %>e-mail</p>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <p class="form-label"><% f.label :password%>Hasło</p>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? "Załóż konto" : "Zapisz", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/users/_user_list.html.erb
<% users.each do |user| %>
    <div class ="row">
        <div class="col-md-8 col-md-offset-2">
            <div class = "well">
                <h4><%= link_to user.name, user_path(user) %></h4>
            </div>
        </div>
    </div>
<%end%>

app/views/users/index.html.erb
<h1 align="center">Zarejestrowani użytkownicy</h1>
<%= render "user_list", users: @users%>

app/views/users/new.html.erb
<h1 align="center">
  Załóż konto w Mioderze!
</h1>

<%= render "form" %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well center">
      <h1><%= @user.name %></h1>
    </div>
  </div>
</div>